### ISSUE TITLE
请问一下 具体tools\lua-bindings 怎么使用 生成导出c++接口的文件

### ISSUE THREAD

**Issue by liyuping6666** [zhongfq/cocos-lua#1]

**Comment by zhongfq** [comment]
目前只支持在mac上导出，因为那个libclang还没有编译win和linux的平台的。tools/lua-bindings目录下有一个buildConf.lua，可以命令行执行 lua buildConf.lua，然后会生成中件文件，输出在tools/lua-bindings/autobuild目录下，执行完成之后就执行lua buildBuilding.lua，就会生成c++接口。如何配置一个导出模块，可以参考tools/lua-bindings/conf/lua-*的文件。如果还是不是很理解，可以加我QQ:34187003
