### ISSUE TITLE
360度圆形进度条 渲染crash

### ISSUE THREAD

**Issue by darklost** [zhongfq/cocos-lua#12]
```

function TestCase:testGProgressBar( )
	-- tips
	self.fairyRoot = fairygui.GRoot:create(display.getRunningScene())
    self.fairyRoot:retain()

	fairygui.UIPackage:addPackage("fairygui/login/login");
    local view = fairygui.UIPackage:createObject("login", "layer_login")
	view:setOpaque(false) -- ignore touch
	view:setPosition(display.cx,display.cy)
    self.fairyRoot:addChild(view)
	local pb = view:getChild("n11")
	local i = math.random(20,100)
	printf("testGProgressBar i=%s",i)
	pb:setValue(i)

	view:getChild("n6"):addEventListener(fairygui.UIEventType.TouchEnd, function(context)
		i=i+1
		pb:setValue(i)
	end)
    -- local scheduler = require(cc.PACKAGE_NAME .. ".scheduler")
    -- scheduler.scheduleGlobal(function (  )
    --     i = i+0.1
    --     if i>100 then
    --         i=0
    --     end
    --     printf("scheduleGlobal i =%s",i)
    --     pb:setValue(i)
    -- end,0.1)
end
```

**Comment by darklost** [comment]
上面是测试代码

**Comment by zhongfq** [comment]
看代码，这个不属于这个项目的，应该是quick社区维护的v4版本。

**Comment by zhongfq** [comment]
另外，v4版本的fairygui的渲染，是我提供的pull request，请问一下，具体是哪里宕机呢？

**Comment by zhongfq** [comment]
> function TestCase:testGProgressBar( )
> 	-- tips
> 	self.fairyRoot = fairygui.GRoot:create(display.getRunningScene())
>     self.fairyRoot:retain()
> 
> 	fairygui.UIPackage:addPackage("fairygui/login/login");
>     local view = fairygui.UIPackage:createObject("login", "layer_login")
> 	view:setOpaque(false) -- ignore touch
> 	view:setPosition(display.cx,display.cy)
>     self.fairyRoot:addChild(view)
> 	local pb = view:getChild("n11")
> 	local i = math.random(20,100)
> 	printf("testGProgressBar i=%s",i)
> 	pb:setValue(i)
> 
> 	view:getChild("n6"):addEventListener(fairygui.UIEventType.TouchEnd, function(context)
> 		i=i+1
> 		pb:setValue(i)
> 	end)
>     -- local scheduler = require(cc.PACKAGE_NAME .. ".scheduler")
>     -- scheduler.scheduleGlobal(function (  )
>     --     i = i+0.1
>     --     if i>100 then
>     --         i=0
>     --     end
>     --     printf("scheduleGlobal i =%s",i)
>     --     pb:setValue(i)
>     -- end,0.1)
> end

我提供pull request修复这个问题了，https://github.com/fairygui/FairyGUI-cocos2dx/pull/77

**Comment by darklost** [comment]
thx,我合并到自己项目测试下
