### ISSUE TITLE
我用xcode12 使用cmake生成macOS项目失败

### ISSUE THREAD

**Issue by fhaoquan** [zhongfq/cocos-lua#13]
下面是报错信息,   
  Command line invocation:
        /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTC_85c40 -configuration Debug -hideShellScriptEnvironment

    User defaults from command line:
        HideShellScriptEnvironment = YES

    Prepare build
    note: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
    === BUILD TARGET cmTC_85c40 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

    Check dependencies
    No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=arm64 arm64e i386 x86_64, EXCLUDED_ARCHS=(
        arm64,
        arm64e
    )).

    ** BUILD FAILED **

**Comment by fhaoquan** [comment]
用cmake能正常生成iOS项目,但是macOS 项目不行.

**Comment by zhongfq** [comment]
这个问题我看一下解决，以前在xcode11上是可以的

**Comment by zhongfq** [comment]
我试了一下，如果是cmake3.16是不行的，我升级到cmake3.18以上就可以了

**Comment by fhaoquan** [comment]
> 我试了一下，如果是cmake3.16是不行的，我升级到cmake3.18以上就可以了

我升级到cmake3.18确实可以了。 谢谢作者。
