### ISSUE TITLE
改由lua gc管理，以实现c++对象的安全访问

### ISSUE THREAD

**Issue by fhaoquan** [zhongfq/cocos-lua#14]
如题, 作者有对上面改进进行测试么?如果有是否能提供测试案例. 感谢回答.

**Comment by zhongfq** [comment]
这里指的是cocos2dx中的Ref子类对象，原来2dx的管理方式是以C++(retain, release)为主的，如果你创建一个Sprite对象，没有进行任何的addChild操作将其挂在其它可视对象上，那么以后使用这个对象，很有可能是宕机的。现在改由lua gc管理的意思，当你push一个Ref对象到lua的时候，底层会主动retain一次，保证你在lua层任何时候访问对象都是安全的，并且如果这个对象没有被任何引用，在gc的时候会主动release。

**Comment by fhaoquan** [comment]
好的，我体验下差别。游戏框架能多点demo演示就更加好了。谢谢作者。

**Comment by zhongfq** [comment]
用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了

**Comment by fhaoquan** [comment]
> 用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了

这游戏框架,作者你有开始商用了么? @zhongfq

**Comment by fhaoquan** [comment]
> > 用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了
> 
> 这游戏框架,作者你有开始商用了么? @zhongfq

感觉你在里面增加了很多内容,但是少了些文档说明看得比较慢.

**Comment by zhongfq** [comment]
> > 用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了
> 
> 这游戏框架,作者你有开始商用了么? @zhongfq

我公司的项目用了快一年多了

**Comment by zhongfq** [comment]
> > > 用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了
> > 
> > 
> > 这游戏框架,作者你有开始商用了么? @zhongfq
> 
> 感觉你在里面增加了很多内容,但是少了些文档说明看得比较慢.

个人建议，如果你以前有用过2dx官方的lua，那就按你原来方式用，不要管我写的lua层部分，我写那个lua层也已经很老的了，不一定好

**Comment by fhaoquan** [comment]
我不是游戏开发人员, 并没有以前游戏lua 库的积累, 我在看quick cocos lua 和你的cocos lua , 现在我想lua 那部分2个 不同开发的内容综合起来方便我使用.

**Comment by fhaoquan** [comment]
> > > > 用法基本上跟官方的没有什么差别，就按原来怎么用，现在怎么用就可以了
> > > 
> > > 
> > > 这游戏框架,作者你有开始商用了么? @zhongfq
> > 
> > 
> > 感觉你在里面增加了很多内容,但是少了些文档说明看得比较慢.
> 
> 个人建议，如果你以前有用过2dx官方的lua，那就按你原来方式用，不要管我写的lua层部分，我写那个lua层也已经很老的了，不一定好

我不是游戏开发人员, 并没有以前游戏lua 库的积累, 我在看quick cocos lua 和你的cocos lua , 现在我想lua 那部分2个 不同开发的内容综合起来方便我使用.

**Comment by zhongfq** [comment]
文档确实比较少写，使用上有什么问题，可以直接问我QQ:34187003

**Comment by fhaoquan** [comment]
> 文档确实比较少写，使用上有什么问题，可以直接问我QQ:34187003

好的,加了.
