### ISSUE TITLE
原来的cocos2d的用法

### ISSUE THREAD

**Issue by fhaoquan** [zhongfq/cocos-lua#15]
原来cocos2d 的用法这样会报下面的错误,我应该怎么用才对呢?
local sharedApplication = cc.Application:getInstance()
local target = sharedApplication:getTargetPlatform()

src/framework/device.lua:19: attempt to index a nil value (field 'Application')
stack traceback:
        src/framework/device.lua:19: in main chunk
        [C]: in function 'require'
        src/framework/init.lua:20: in main chunk
        [C]: in function 'require'
        src/app/MyApp.lua:4: in main chunk
        [C]: in function 'require'
        src/main.lua:12: in function 'main'
        src/bootstrap.lua:67: in function <src/bootstrap.lua:65>
        [C]: in function 'xpcall'
        src/bootstrap.lua:69: in field 'onComplete'
        src/bootstrap.lua:84: in function <src/bootstrap.lua:22>

**Comment by zhongfq** [comment]
local Application = require 'cc.Application'
local sharedApplication = Application.getInstance()
local target = sharedApplication:getTargetPlatform()

**Comment by fhaoquan** [comment]
> local Application = require 'cc.Application'
> local sharedApplication = Application.getInstance()
> local target = sharedApplication:getTargetPlatform()

原来现在换成了要require进来.

**Comment by zhongfq** [comment]
还有一般情况下，会为getTargetPlatform()这样的方法生成一个属性，可以这样访问: local target = sharedApplication.targetPlatform

**Comment by fhaoquan** [comment]
> 还有一般情况下，会为getTargetPlatform()这样的方法生成一个属性，可以这样访问: local target = sharedApplication.targetPlatform

我直接把cocos2dx 4.0 的lua 库引用发现math.pow 出现以下问题
src/cocos/cocos2d/Cocos2dConstants.lua:622: attempt to call a nil value (field 'pow')
stack traceback:
        src/cocos/cocos2d/Cocos2dConstants.lua:622: in main chunk
        [C]: in function 'require'
        src/cocos/init.lua:26: in main chunk
        [C]: in function 'require'
        src/main.lua:2: in main chunk
        [C]: in function 'require'
        src/bootstrap.lua:66: in function <src/bootstrap.lua:65>
        [C]: in function 'xpcall'
        src/bootstrap.lua:69: in field 'onComplete'
        src/bootstrap.lua:84: in function 'main'

**Comment by fhaoquan** [comment]
还有这个AsyncTaskPool 好像没导出吧
src/cocos/cocos2d/Cocos2dConstants.lua:6: module 'cc.AsyncTaskPool' not found:
        no field package.preload['cc.AsyncTaskPool']
        no file 'src/cc/AsyncTaskPool.lua'
        no file 'cc/AsyncTaskPool.lua'
        no file '/usr/local/share/lua/5.4/cc/AsyncTaskPool.lua'
        no file '/usr/local/share/lua/5.4/cc/AsyncTaskPool/init.lua'
        no file '/usr/local/lib/lua/5.4/cc/AsyncTaskPool.lua'
        no file '/usr/local/lib/lua/5.4/cc/AsyncTaskPool/init.lua'
        no file './cc/AsyncTaskPool.lua'
        no file './cc/AsyncTaskPool/init.lua'
        no file '/usr/local/lib/lua/5.4/cc/AsyncTaskPool.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './cc/AsyncTaskPool.so'
        no file '/usr/local/lib/lua/5.4/cc.so'
        no file '/usr/local/lib/lua/5.4/loadall.so'
        no file './cc.so'

**Comment by zhongfq** [comment]
没有导出，这个AsyncTaskPool在lua层没有意义，lua的代码不能在异步执行

**Comment by fhaoquan** [comment]
> 没有导出，这个AsyncTaskPool在lua层没有意义，lua的代码不能在异步执行

绑定代码生成
tools/lua-bindings提供代码生成脚本，具体的例子可以参考tools/lua-bindings/conf目前下的配置文件，如果你所使用的平台执行有问题，那么你可以自己编译clang动态库，编译参见lua-clang

这个绑定怎么用有说明吗? 该怎么运行.

**Comment by zhongfq** [comment]
> > 还有一般情况下，会为getTargetPlatform()这样的方法生成一个属性，可以这样访问: local target = sharedApplication.targetPlatform
> 
> 我直接把cocos2dx 4.0 的lua 库引用发现math.pow 出现以下问题
> src/cocos/cocos2d/Cocos2dConstants.lua:622: attempt to call a nil value (field 'pow')
> stack traceback:
> src/cocos/cocos2d/Cocos2dConstants.lua:622: in main chunk
> [C]: in function 'require'
> src/cocos/init.lua:26: in main chunk
> [C]: in function 'require'
> src/main.lua:2: in main chunk
> [C]: in function 'require'
> src/bootstrap.lua:66: in function <src/bootstrap.lua:65>
> [C]: in function 'xpcall'
> src/bootstrap.lua:69: in field 'onComplete'
> src/bootstrap.lua:84: in function 'main'

lua5.3以后的版本都没有math.pow方法了

**Comment by fhaoquan** [comment]
> > > 还有一般情况下，会为getTargetPlatform()这样的方法生成一个属性，可以这样访问: local target = sharedApplication.targetPlatform
> > 
> > 
> > 我直接把cocos2dx 4.0 的lua 库引用发现math.pow 出现以下问题
> > src/cocos/cocos2d/Cocos2dConstants.lua:622: attempt to call a nil value (field 'pow')
> > stack traceback:
> > src/cocos/cocos2d/Cocos2dConstants.lua:622: in main chunk
> > [C]: in function 'require'
> > src/cocos/init.lua:26: in main chunk
> > [C]: in function 'require'
> > src/main.lua:2: in main chunk
> > [C]: in function 'require'
> > src/bootstrap.lua:66: in function <src/bootstrap.lua:65>
> > [C]: in function 'xpcall'
> > src/bootstrap.lua:69: in field 'onComplete'
> > src/bootstrap.lua:84: in function 'main'
> 
> lua5.3以后的版本都没有math.pow方法了

嗯, 这个我查了, 我知道了, 那个tools/lua-bindings提供代码生成脚本怎么用?

**Comment by zhongfq** [comment]
> > 没有导出，这个AsyncTaskPool在lua层没有意义，lua的代码不能在异步执行
> 
> 绑定代码生成
> tools/lua-bindings提供代码生成脚本，具体的例子可以参考tools/lua-bindings/conf目前下的配置文件，如果你所使用的平台执行有问题，那么你可以自己编译clang动态库，编译参见lua-clang
> 
> 这个绑定怎么用有说明吗? 该怎么运行.

# window cmd，mac or linux terminal
cd tools/lua-bindings
lua buildConfig.lua     # 自动扫描类，生成扫描结果
lua buildBindings.lua   # 执行导出lua bindings

**Comment by fhaoquan** [comment]
> > > 没有导出，这个AsyncTaskPool在lua层没有意义，lua的代码不能在异步执行
> > 
> > 
> > 绑定代码生成
> > tools/lua-bindings提供代码生成脚本，具体的例子可以参考tools/lua-bindings/conf目前下的配置文件，如果你所使用的平台执行有问题，那么你可以自己编译clang动态库，编译参见lua-clang
> > 这个绑定怎么用有说明吗? 该怎么运行.
> 
> # window cmd，mac or linux terminal
> cd tools/lua-bindings
> lua buildConfig.lua # 自动扫描类，生成扫描结果
> lua buildBindings.lua # 执行导出lua bindings

这个我在下载中, 还有cc.load 这个是怎么用了?

**Comment by zhongfq** [comment]
> 这个我在下载中, 还有cc.load 这个是怎么用了?

没有cc.load这个东西吧

**Comment by fhaoquan** [comment]
> > 这个我在下载中, 还有cc.load 这个是怎么用了?
> 
> 没有cc.load这个东西吧

我是看了原来的cocos2dx lua 里面有这玩意.

**Comment by zhongfq** [comment]
> > 没有cc.load这个东西吧
> 
> 我是看了原来的cocos2dx lua 里面有这玩意.

我一直没有用过。。。
