### ISSUE TITLE
测试用例的骨骼动画无法播放

### ISSUE THREAD

**Issue by bsqgm** [zhongfq/cocos-lua#22]
在win10平台下，使用vs2019编译8月12号main分支下最新的代码，运行后发现报错

[14:42:27] create scene: SpineTest
[14:42:27] --------------------LUA ERROR--------------------
src/test\SpineTest.lua:10: Invalid image
stack traceback:
	[C]: in field 'new'
	src/test\SpineTest.lua:10: in function 'ctor'
	src/xgame\class.lua:109: in local 'create'
	src/xgame\class.lua:112: in function 'new'
	src/xgame\SceneStack.lua:83: in function '_doStartScene'
	src/xgame\SceneStack.lua:38: in function 'startScene'
	src/xgame\xGame.lua:108: in local 'callback'
	src/xgame\xGame.lua:92: in method 'loadAssets'
	src/xgame\xGame.lua:107: in method '_loadSceneAssets'
	src/xgame\xGame.lua:117: in method 'startScene'
	src/main.lua:9: in function 'main'
	src/bootstrap.lua:67: in function <src/bootstrap.lua:65>
	[C]: in function 'xpcall'
	src/bootstrap.lua:69: in field 'onComplete'
	src/bootstrap.lua:84: in function <src/bootstrap.lua:22>

调试后发现，读取.atlas文件格式时，没有正确识别到该文件内容，去掉.atlas首行空格后可以正常识别。但是之后.skel读取也出现问题了，内容中的spine版本信息明显没有正确读取。

将版本回退到fc105ca93d5c51d1fcf98acdaf01f4c502d00318，骨骼动画可以正常播放，怀疑是spine升级导致原本的spine文件无法使用了。

另外，请教下如何用vscode调试项目？使用了luaide插件，然后init.lua取消这段注释代码。断点仍然无法生效，是哪里还需要处理吗？
![image](https://user-images.githubusercontent.com/37140581/129167952-f6084680-504a-4f1a-9bef-b1b67d3cb4b7.png)

**Comment by zhongfq** [comment]
spine的测试更新了

**Comment by zhongfq** [comment]
luasocket没有兼容lua5.4.3，如果你需要调试，下载lua5.4.2以下的版本，覆盖libxgame/src/lua下的代码

**Comment by bsqgm** [comment]
试了下，可以正常播放测试用例的骨骼动画了。替换成lua5.3之后也可以正常调试了。感谢：）
