### ISSUE TITLE
ui.inflate创建指定字体时会提示找不到字体文件

### ISSUE THREAD

**Issue by bsqgm** [zhongfq/cocos-lua#24]
1、注册两个字体文件
![image](https://user-images.githubusercontent.com/37140581/131959266-1cbc20b7-d617-47b8-958b-700f47c78ba0.png)
2、创建指定字体的label
![image](https://user-images.githubusercontent.com/37140581/131959348-f985fe49-c98a-487b-8d19-fb1921d1829c.png)
3、提示
font 'res/ui/Kenney Blocks.ttf' not found

查看调用堆栈，这里调用了两次resolve
![image](https://user-images.githubusercontent.com/37140581/131959551-5efbac36-0faf-4e39-abf5-511ce3f1af7f.png)

**Comment by zhongfq** [comment]
我改好了

另外问一下，为啥用手动创建UI呢，其实可以使用fairygui的

**Comment by bsqgm** [comment]
好的：）
主要是两个原因，一个是fairygui还不太熟练，另外一个就是测试用的ui比较简单，感觉没有必要再fairygui里创建。
