### ISSUE TITLE
关于lua-websocket

### ISSUE THREAD

**Issue by sishui** [zhongfq/cocos-lua#26]
https://github.com/zhongfq/cocos-lua/blob/cbad3eb61c75bbb3f9fdba866cdc30d0dac54af8/frameworks/libxgame/src/lua-bindings/lua_conv.cpp#L2075

这里似乎不应该用 lua_pushstring 而应该用 lua_pushlstring，如果websocket收到的数据是bin且中间有'\0'，就会被截断

**Comment by zhongfq** [comment]
修复了
