### ISSUE TITLE
想获取用户手机的唯一设备号，这个函数runtime.getDeviceInfo可以吗？

### ISSUE THREAD

**Issue by bsqgm** [zhongfq/cocos-lua#27]
在我自己的android手机上是可以获取到一个字符串，但是不确定这个字符串是否唯一。
查了下这几个参数，看起来不像是唯一的。
![image](https://user-images.githubusercontent.com/37140581/137773580-dac9e747-4339-4a65-a0b7-46b8987080e2.png)
现在该如何操作，是在AppContext.java里仿照runtime.getDeviceInfo自己用android.os.Build的参数拼一个吗？

**Comment by zhongfq** [comment]
> 在我自己的android手机上是可以获取到一个字符串，但是不确定这个字符串是否唯一。
> 查了下这几个参数，看起来不像是唯一的。
> ![image](https://user-images.githubusercontent.com/37140581/137773580-dac9e747-4339-4a65-a0b7-46b8987080e2.png)
> 现在该如何操作，是在AppContext.java里仿照runtime.getDeviceInfo自己用android.os.Build的参数拼一个吗？

这个只是获取设备的简单信息，如果需要获取唯一设备号，得自己写一个，在AppContext.java的写一个咯，在lua层可以使用luaj调用java的静态方法
