### ISSUE TITLE
cocos2d::Vector，cocos2d::Map，Color3B等没有看到导出，请问如何使用？

### ISSUE THREAD

**Issue by dream2014** [zhongfq/cocos-lua#30]
其中Color3B我看前面提问有说采用0xFFFFFFFF的方式。如果采用Color3B.new(r, g, b)更为直观。
一些常见类型，不知道如何在lua中使用，是否需要导出成class更方便？
typedef 'cocos2d::Data'
typedef 'cocos2d::Mat4'
typedef 'cocos2d::Vector'
    .conv 'olua_$$_array'
typedef 'cocos2d::Color3B'
typedef 'cocos2d::Color4B'
typedef 'cocos2d::Color4F'
typedef 'cocos2d::Value'
typedef 'cocos2d::ValueMap'
typedef 'cocos2d::ValueMapIntKey'
typedef 'cocos2d::ValueVector'
typedef 'cocos2d::Map'
    .conv 'olua_$$_map'
typedef 'cocos2d::network::WebSocket::Data'

typedef 'cocos2d::Rect'
    .vars '4'

typedef 'cocos2d::EventListener::ListenerID'
    .decltype 'std::string'

**Comment by zhongfq** [comment]
这个我可以做一个编译选项，可以选择原来的方式，弄好了告诉你

**Comment by zhongfq** [comment]
cocos2d::Vector，cocos2d::Map 已经退化为 lua table了：
static int _cocos2d_Node_getChildren(lua_State *L)
{
    olua_startinvoke(L);

    cocos2d::Node *self = nullptr;

    olua_to_cppobj(L, 1, (void **)&self, "cc.Node");

    // @addref(children |) Vector<cocos2d::Node *> &getChildren()
    cocos2d::Vector<cocos2d::Node *> &ret = self->getChildren();
    int num_ret = olua_push_array<cocos2d::Node *>(L, &ret, [L](cocos2d::Node *value) {
        olua_push_cppobj(L, value, "cc.Node");
    });

    // insert code after call
    olua_addref(L, 1, "children", -1, OLUA_MODE_MULTIPLE | OLUA_FLAG_TABLE);

    olua_endinvoke(L);

    return num_ret;
}
直接使用 olua_push_array 处理了

**Comment by zhongfq** [comment]
Color3B，Color4B，Color4F 这三个东西，目前处理方式是都是由整数代替，形式为：
Color3B -> 0xRRGGBB，Color4B|Color4F -> 0xRRGGBBAA，

node.color = 0xFF3CAB

如果你喜欢原来的使用方式，可以在lua层实现原来table结构，然后搞个 toInteger 方法，转为 0xRRGGBBAA 的形式

node.color = Color3B.new(r, g, b).toInteger()

**Comment by zhongfq** [comment]
因为我个人习惯 0xFFFFFFFF 的形式，所以当初导出的时候就采用了这个形式，其实很多软件的色彩数值也是这个形式的

**Comment by zhongfq** [comment]
我实现了可选项，代码已更新，你可以将:
option(CCLUA_FEATURE_INTCOLOR "Support integer color" ON)
改为
option(CCLUA_FEATURE_INTCOLOR "Support integer color" OFF)
以使用原来的形式

**Comment by dream2014** [comment]
采用table的方式传递array，map，使用起来很方便，帅气！
感谢支持CCLUA_FEATURE_INTCOLOR 开关！

**Comment by zhongfq** [comment]
如果有使用的疑问，可以在QQ(34187003)上直接问我
