### ISSUE TITLE
2022-5-15获取的版本，ClassTest无法正常运行，提示如下！

### ISSUE THREAD

**Issue by dream2014** [zhongfq/cocos-lua#31]
错误信息：
#1 argument error, expect: 'cc.Node', got 'table'

classtest出错位置：
local my = MyNode.new('a', 'b', 'c')   

class中错误位置：
new的递归create过程中，执行cc.Node的ctor时，异常。  
if c.ctor then 访问c.ctor

**Comment by zhongfq** [comment]
这个问题修复了，原因是我之前为Node添加了默认了索引行为，用于方便获取子节点（local label = node.label 等价于 local label = node:getChildByName('label')）

**Comment by dream2014** [comment]
新版本经测试，功能正常！感谢！
