### ISSUE TITLE
关于 PluginManager

### ISSUE THREAD

**Issue by sishui** [zhongfq/cocos-lua#6]
请问下  PluginManager 里的 start 似乎没调用？我找了一下没找到

**Comment by zhongfq** [comment]
这个本应该在AppEntry.java 调用的，由于我还没有全部把v3的代码迁移过来，所以你可能没有找到。这是v3的https://github.com/zhongfq/cocos-lua/blob/bbcf7e46db5b13a9e73a34d9f559b42c05b64338/runtime-src/proj.android/app/src/com/codetypes/hellolua/AppEntry.java#L14

**Comment by zhongfq** [comment]
最近在忙libclang在window上的编译，现在可以在windows cmd上执行lua bindings的代码导出了

**Comment by sishui** [comment]
好的 谢谢~，空了 我对比下v3
