### ISSUE TITLE
ui显示问题请教

### ISSUE THREAD

**Issue by xjn9854262** [zhongfq/cocos-lua#8]
很感谢作者贡献这个项目，让我能开箱即用。
但现在我在使用fgui的示例，Transition这个里面有一个g4动画用到fnt字体，我看到字体是不显示的，是不是这块不支持fnt字体呢

**Comment by zhongfq** [comment]
支持的，你要使用UIConfig.registerFont api，具体看一下UIConfig.h文件

**Comment by xjn9854262** [comment]
> 支持的，你要使用UIConfig.registerFont api，具体看一下UIConfig.h文件

感谢你的回复，谢谢。
